.github/workflows/ci.yml
.github/workflows/codeql-analysis.yml

Setup CI: Unit Tests

---

.github/workflows/ci.yml
app/caldav/index.spec.ts
package-lock.json
package.json

Use Testcontainers to start Baikal

---

.github/workflows/ci.yml
app/caldav/index.spec.ts
cypress.json
cypress/integration/landing.spec.ts
cypress/integration/test.spec.ts
cypress/support/url.ts
cypress/tsconfig.json
jest.config.js
package-lock.json
package.json
test/skip-without-docker.ts
tsconfig.json

Closes: #27 
This PR sets up Cypress and the Cypress dashboard.
It doesn't add any non-trivial tests, which should be written after the Bootstrap-Transition.

Setup Cypress for E2E tests

---

utils/singleton.spec.ts
utils/singleton.ts

This PR adds a `singleton` function that allows you to use the singleton pattern without having to resort to classes. May be helpful for the email code.

Add singleton utility

---

app/components/Navbar.tsx
app/meetings/components/Meetings.tsx
app/meetings/components/creationSteps/Advanced.tsx
app/meetings/components/creationSteps/Availability.tsx
app/meetings/components/creationSteps/General.tsx
app/meetings/components/creationSteps/Schedule.tsx
app/meetings/mutations/addMeeting.tsx
app/meetings/pages/meeting/create.tsx
app/meetings/types.tsx

This PR contains my review of the meetings and components folders.

Refactor meetings and components folder

---

app/auth/pages/login.tsx
app/auth/pages/signup.tsx

This PR contains small refactorings to the `auth` folder.

Refactor auth folder

---

app/pages/index.tsx
main.scss

Closes: #123 
Fresh home page for logged in users 😎

more compelling content for logged in home

---

.github/workflows/ci.yml
.gitignore
app/api/__coverage__.ts
babel.config.js
cypress.json
cypress/.gitignore
cypress/plugins/index.js
cypress/rewrite-coverage-sources.js
cypress/support/index.ts
package-lock.json
package.json

This PR adds the required configuration to incorporate the e2e tests in our coverage reports.

Incorporate Cypress tests in Coverage Reports

---

app/meetings/components/schedules/AddScheduleModal.tsx

fix schedule editing and add blocking a day option

---

app/pages/index.tsx

add imprint to home

---

app/appointments/pages/schedule/[username]/[slug].tsx
app/appointments/queries/getTimeSlots.ts

quickfix timeslots working

---

app/auth/validations.ts
app/users/components/UserDataForm.tsx
app/users/mutations/updateUserData.tsx
app/users/pages/settings.tsx

Closes: #148 
Enables updating the user information from the settings page

Update user data

---

app/layouts/Layout.tsx
app/pages/index.tsx

Fix some design bugs

---

app/users/components/AddCalendar.tsx

add caldav warning

---

app/auth/validations.ts
app/meetings/components/creationSteps/General.tsx
app/meetings/components/schedules/AddScheduleModal.tsx
app/users/components/AddCalendar.tsx
cypress/integration/meetings-flow.spec.ts

Input validation

---

app/appointments/pages/schedule/[username]/[slug].tsx
app/auth/mutations/signup.ts
app/auth/pages/signup.tsx
app/auth/validations.ts

Aligns validation of booking form with other validations using zod

Input validation booking

---

app/meetings/components/Meetings.tsx
app/meetings/components/schedules/AllSchedules.tsx
app/meetings/mutations/deleteMeeting.tsx
app/meetings/mutations/deleteSchedule.tsx

Delete schedule presets

---

app/meetings/components/schedules/AddScheduleModal.tsx

Changes of #190 were overwritten at some point. This solves the problem (again and definetly) :)

explicit blocked handling in schedule

---

app/users/mutations/deleteUser.tsx

Fix user deletion

---

app/pages/index.tsx

Fix typo on homepage

---

app/appointments/queries/getTimeSlots.ts
app/calendar/googlecalendar/mutations/createCalendarCredentials.ts

fixed merging of multiple calendars
